name: clinicapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  zoom_tap_animation: ^1.1.0
  flutter_svg: ^2.0.10+1
  card_swiper: ^3.0.1
  shared_preferences: ^2.3.2
  lottie: ^3.1.2
  smooth_page_indicator: ^1.2.0+3
  easy_localization: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/lotties/
    - assets/fonts/
    - assets/lang/

  fonts:
    - family: LexendTera
      fonts:
        - asset: assets/fonts/LexendTera.ttf
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Black.ttf
